### ISSUE TITLE
IHU: Test IHU/Subsystem I2C API

### ISSUE THREAD

**Issue by ElijahBryonCraig** [CougsInSpace/CougSat1-Software#255] opened 2018-11-04 22:33 UTC
This is done with a mock ADCS. The mock ADCS is used to test the efficacy of the IHU/SS I2C API by having reliable and clear responses from the subsystem.

**Comment by WattsUp** [comment] 2018-11-06 20:08
Duplicate of #94 #95 #124, abandoning

**Closed by WattsUp** 2018-11-06 20:08 UTC
Labels: IHU, Intermediate, Tests
