### ISSUE TITLE
IHU: IHU/Subsystem I2C API

### ISSUE THREAD

**Issue by ElijahBryonCraig** [CougsInSpace/CougSat1-Software#254] opened 2018-11-04 22:30 UTC
Design and implement a reliable and clear API to communicate from IHU to ADCS, PMIC, and IFJR subsystems using designated addresses listed in each respective systems interface protocols.

**Comment by WattsUp** [comment] 2018-11-06 20:07
Duplicate of #11 #12 #13, abandoning

**Closed by WattsUp** 2018-11-06 20:07 UTC
